name: Test

on:
  - pull_request
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Set up Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn --immutable

      - name: Test
        run: yarn test
